### ISSUE TITLE
P5built-ins

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#109] opened 2018-08-03 01:50 UTC
Module [P5built-ins](https://modules.perl6.org/dist/P5built-ins) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by lizmat** [comment] 2018-08-03 11:41
This was probably due to `P5localtime` / `P5readlink` failing.  `P5localtime` has been fixed, `P5readlink` I cannot reproduce.  So closing this one.

**Comment by AlexDaniel** [comment] 2018-08-03 14:14
@lizmat toaster says:
```
===> Failed to find dependencies: P5tie
```

Is it actually fixed?

**Comment by lizmat** [comment] 2018-08-03 15:01
This is weird: `P5tie` seems to have fallen out of modules.perl6.org?  Yet, it installs fine with zef:

$ zef install P5tie --force-install
===> Searching for: P5tie
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Testing: P5tie:ver<0.0.9>:auth<cpan:ELIZABETH>
===> Testing [OK] for P5tie:ver<0.0.9>:auth<cpan:ELIZABETH>
===> Installing: P5tie:ver<0.0.9>:auth<cpan:ELIZABETH>

**Comment by lizmat** [comment] 2018-08-03 15:45
Turns out that while I was cleaning up some old versions on PAUSE, I accidentally deleted the `P5tie` `.meta` file, while leaving the `.readme` and the `.tar.gz`.  I've uploaded a new version of `P5Tie`, so now it has a `.meta` again on PAUSE.  Pretty sure that solves the problem once everything has percolated through the various caches.

**Closed as completed by lizmat** 2018-08-03 15:45 UTC
