### ISSUE TITLE
Audio::Convert::Samplerate

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#555] opened 2019-02-09 16:57 UTC
Module [Audio::Convert::Samplerate](https://modules.perl6.org/dist/Audio::Convert::Samplerate) cannot be installed (`Fail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Audio::Convert::Samplerate
===> Found: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0> to /home/alex/Blin/data/zef-data/tmp/1549727355.23778.4209/Audio-Convert-Samplerate-0.0.8.tar.gz
===> Extraction [OK]: Audio::Convert::Samplerate to /home/alex/Blin/data/zef-data/store/Audio-Convert-Samplerate-0.0.8.tar.gz
===> Testing: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
t/001-meta.t ......... ok
t/001-use.t .......... ok
# testing with samplerate version libsamplerate.0.1.9.c.2002.2008.Erik.de.Castro.Lopo
t/010-constructor.t .. ok
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 546 frames'
# at t/020-process.t line 43
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 44
# Failed test 'got the right sort of array back'
# at t/020-process.t line 45
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 546 frames'
# at t/020-process.t line 69
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 70
# Failed test 'got the right sort of array back'
# at t/020-process.t line 71
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 546 frames'
# at t/020-process.t line 95
# Can only store CArray attribute in CArray slot in CStruct
Use of uninitialized value of type Any in numeric context
  in block  at t/020-process.t line 96
# Failed test 'got the right sort of array back'
# at t/020-process.t line 97
# Actual type: Any
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 546 frames (floats as an array)'
# at t/020-process.t line 122
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 546 frames (shorts as an array)'
# at t/020-process.t line 148
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 1024 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Failed test 'process 546 frames (ints as an array)'
# at t/020-process.t line 174
# Can only store CArray attribute in CArray slot in CStruct
# Looks like you failed 198 tests of 216
t/020-process.t ...... 
Dubious, test returned 198 (wstat 50688, 0xc600)
Failed 198/216 subtests 

Test Summary Report
-------------------
t/020-process.t    (Wstat: 50688 Tests: 216 Failed: 198)
  Failed tests:  3-46, 50-93, 97-140, 144-165, 169-190, 194-215
  Non-zero exit status: 198
Files=4, Tests=222, 14 wallclock secs ( 0.09 usr  0.01 sys + 12.02 cusr  0.39 csys = 12.51 CPU)
Result: FAIL
===> Testing [FAIL]: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
Failed to get passing tests, but continuing with --force-test
===> Installing: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
===> Install [OK] for Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>

````````````````````````````````````````````````````````

Ping @jonathanstowe

**Comment by jonathanstowe** [comment] 2019-02-09 18:43
Looks like a rakudo regression to me.  It test fine in https://travis-ci.org/jonathanstowe/Audio-Convert-Samplerate . Will investigate.

**Comment by AlexDaniel** [comment] 2019-02-09 18:43
Actually, yeah:

Audio::Convert::Samplerate – Fail, Bisected: https://github.com/rakudo/rakudo/commit/ada116ef99a2a68dc6e1f77f2c3959f1d4e49e0d

Please file a bug report.

**Comment by jonathanstowe** [comment] 2019-02-09 19:27
Submitted https://github.com/rakudo/rakudo/issues/2687

**Comment by jonathanstowe** [comment] 2019-02-12 14:42
Fixed with https://github.com/rakudo/rakudo/commit/30fc5146ca875a289774c4ce1f0c43c6204b921c

```
jns:~/me/Perl6-Modules/Audio-Convert-Samplerate$ perl6 -v
This is Rakudo version 2018.12-296-g30fc5146c built on MoarVM version 2018.12-94-g2eab275df
implementing Perl 6.d.
jns:~/me/Perl6-Modules/Audio-Convert-Samplerate$ zef test . --debug
===> Testing: Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
Testing with plugin: Zef::Service::TAP+{<anon|1>}
t/001-meta.t ......... ok
t/001-use.t .......... ok
# testing with samplerate version libsamplerate.0.1.9.c.2002.2008.Erik.de.Castro.Lopo
t/010-constructor.t .. ok
t/020-process.t ...... ok
All tests successful.
Files=4, Tests=222,  3 wallclock secs
Result: PASS
===> Testing [OK] for Audio::Convert::Samplerate:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
```

**Closed as completed** 2019-02-12 14:42 UTC
Labels: rakudobug
